### ISSUE TITLE
🚨Highly Frequent Ad Request or Frequent Ad dismiss causing reduction in stats, revenue

### ISSUE THREAD

**Issue by ycv005** [AppLovin/AppLovin-MAX-Flutter#122] opened 2023-09-17 08:28 UTC
### MAX Plugin Version

applovin_max: ^3.2.0

### Flutter Version

3.13.1

### Device/Platform Info

Android

### Current Behavior

Hello AppLovin Team (@thomasmso , @alhiwatan & other),
First of all thanks for the flutter plugin. I am here to point out very important issue 🚨 for the highly frequent ad request or ad dismiss which is ultimately causing reduction in stats (eCPM, viewability & other) and revenue. 

Ad Type
- Banner & Mrec

Simple Scenario
- Open an App page, then Banner Ads show, then scroll in such a way Ad is away from view port & when come back, ad disappear and the ads reload again. So, Ads are being hidden or disappear when going out of viewport of that particular Ad and coming back.  [App LINK](https://play.google.com/store/apps/details?id=com.topbestof.qwizb&pcampaignid=web_share)

Video link of Issue - [LINK](https://drive.google.com/file/d/1DokDQjiNXee0aD7IuQ7OrztuqqEU8X2V/view?usp=drivesdk)

### Expected Behavior

Banner Ads & Mrec Ads show be reload/hide when refresh time comes that is 30 -90 sec and not because going out of viewport.

### How to Reproduce

Ad Type Implementation

```

class BannerAdContainer extends StatefulWidget {
  final CustomBannerSize? customBannerSize;
  final double bannerHeight;
  final Widget? optionalWidget;
  final Function? onTap;
  const BannerAdContainer(
      {super.key,
      this.customBannerSize,
      this.onTap,
      this.bannerHeight = 0,
      this.optionalWidget});

  @override
  _BannerAdContainer createState() => _BannerAdContainer();
}

class _BannerAdContainer extends State<BannerAdContainer> {
  // BannerAd? _googleBannerAd;
  AdManagerBannerAd? _googleBannerAd;
  CustomBannerSize? _bannerSize;
  AdSize? currentSize;
  MaxAdView? maxBanner;
  Widget? maxAdBanner;

  @override
  void initState() {
    super.initState();
    if (widget.customBannerSize == null) {
      _bannerSize = CustomBannerSize.medium;
    } else {
      _bannerSize = widget.customBannerSize;
    }
    currentSize = AdSize.largeBanner;
    _initBannerAd();
  }

  @override
  void dispose() {
    _googleBannerAd?.dispose();
    super.dispose();
  }

  void _initBannerAd() {
    Future.delayed(Duration.zero, () {
      final systemConfigCubit = context.read<SystemConfigCubit>();
      if (systemConfigCubit.isAdsEnable()) {
        //is google ad enable or not
        if (systemConfigCubit.adsType() == 1) {
          _createGoogleBannerAd();
        } else if (systemConfigCubit.adsType() == 4) {
          // This is done in build stage.
          _createAppLovinBannerAd();
        }
      }
    });
  }

  // MaxAdView?
  void _createAppLovinBannerAd() {
    String adUnit = context
        .read<SystemConfigCubit>()
        .applovinBannerId(bannerType: _bannerSize!);
    if (adUnit.isEmpty) {
      return null;
    }
    Map<String, String>? extraParameters = {
      "adaptive_banner": "true",
    };
    double deviceWidth = MediaQuery.of(context).size.width;
    maxAdBanner =
        // return
        MaxAdView(
      adUnitId: adUnit,
      // visible: false,
      isAutoRefreshEnabled: true,
      customData: context.read<UserDetailsCubit>().userId(),
      extraParameters: extraParameters,
      adaptiveBannerWidth: deviceWidth,
      adFormat: CustomBannerSize.large == _bannerSize
          ? AdFormat.mrec
          : AdFormat.banner,
      listener: AdViewAdListener(
          onAdLoadedCallback: (ad) {
            setState(() {});
          },
          onAdLoadFailedCallback: (adUnitId, error) {
            // implement Banner Native Ads.
            setState(() {
              maxAdBanner = NativeAdContainer(
                width: deviceWidth,
                height: CustomBannerSize.large == _bannerSize ? 250 : 50,
              );
            });
          },
          onAdClickedCallback: (ad) {},
          onAdExpandedCallback: (ad) {},
          onAdCollapsedCallback: (ad) {}),
    );
  }

  Future<void> _createGoogleBannerAd() async {
    // coder for Google Banner Ad.
  }

  @override
  Widget build(BuildContext context) {
    final sysConfig = context.read<SystemConfigCubit>();
    if (sysConfig.isAdsEnable()) {
      if (sysConfig.adsType() == 1) {
        return _googleBannerAd != null
            ? SizedBox(
                width: MediaQuery.of(context).size.width,
                height: currentSize == AdSize.fluid
                    ? min(50, widget.bannerHeight)
                    : _googleBannerAd!.sizes[0].height.toDouble(),
                child: AdWidget(ad: _googleBannerAd!),
              )
            : widget.optionalWidget ?? const SizedBox();
      } else if (sysConfig.adsType() == 4) {
        return maxAdBanner //_createAppLovinBannerAd()
            ??
            const SizedBox();
      }
    }
    return const SizedBox();
  }
}

```

**Comment by Nikolaisd** [comment] 2023-09-19 11:43
You can resolve this by adding your Banner ad in an overlay entry. 
Just remember to adjust your UI accordingly

  entry = OverlayEntry(
      builder: (context) => SafeArea(
          child: Align(
        alignment: Alignment.topCenter,
        child: MaxAdView(
            isAutoRefreshEnabled: true,
            adUnitId: adBannerID,
            adFormat: AdFormat.banner,
            listener: AdViewAdListener(
                onAdLoadedCallback: (ad) {},
                onAdLoadFailedCallback: (adUnitId, error) {
                  log.e(
                      'Banner ad failed load - error  ${error.code} and message: ${error.message}');
                },
                onAdClickedCallback: (ad) {},
                onAdExpandedCallback: (ad) {},
                onAdCollapsedCallback: (ad) {},
                onAdRevenuePaidCallback: (ad) {
                })),
      )),
    );
    final adOverlay = Overlay.of(context);
    adOverlay.insert(entry!);

**Comment by alhiwatan** [comment] 2023-09-20 03:55
@Nikolaisd, thanks for your comment.   I guess [AutomaticKeepAliveClientMixin](https://api.flutter.dev/flutter/widgets/AutomaticKeepAliveClientMixin-mixin.html) is also useful for keeping the state.   Since we want our library to be as lean as possible, we don't have a plan to have this feature in the library for now.

**Comment by ycv005** [comment] 2023-09-20 06:29
@thomasmso @alhiwatan , let say, I could fix it manually but this will put not good image of applovin with other bidding platform and user/seller, like frequently getting lot of request or frequent ad dismissible or low viewability. Let me know, if I am wrong. I have tried testing  [unity_ads](https://pub.dev/packages/unity_ads_plugin) and [google mobile ads](https://pub.dev/packages/google_mobile_ads) but they were fine.

**Comment by ycv005** [comment] 2023-09-25 15:29
@alhiwatan @thomasmso I have implemented AutomaticKeepAliveClientMixin and issue is resolved. But, I have gained info and my revenue team is concerned because of the banner and native ads performance. Thus causing lower CPM and other stats, ultimately causing lower revenue.
Here is the analytics from this month and last week, showing lot of unfilled ads

![WhatsApp Image 2023-09-22 at 16 33 03](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/26734819/b74a7488-9636-462e-b86e-deb2fc8a5e2c)
![WhatsApp Image 2023-09-25 at 20 19 34 (1)](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/26734819/520aaf91-06ec-4a06-9b24-152bd433d4a6)

**Comment by ycv005** [comment] 2023-09-26 11:14
@thomasmso @alhiwatan This is causing big issue. Revenue is huge effected.

**Comment by ycv005** [comment] 2023-10-03 04:49
@thomasmso @alhiwatan any update on this ?

**Comment by ycv005** [comment] 2023-10-03 11:24
@thomasmso @alhiwatan I have added AutomaticKeepAliveClientMixin 1 week back, the issue of ad disappearing and reloading new when coming back in view port from scroll was resolved. But, still no. of request or no. of unfilled impression are too high. We have started reducing banner ads due to this issue, because it is creating bad impression for our app.

**Comment by alhiwatan** [comment] 2023-12-11 06:03
Closing since the issue is resolved with `AutomaticKeepAliveClientMixin`.    You can increase the impression rate by adding more networks.

**Closed** 2023-12-11 06:19 UTC
Labels: bug
