### ISSUE TITLE
Platform channel exception: Reply already submitted

### ISSUE THREAD

**Issue by lesnitsky** [AppLovin/AppLovin-MAX-Flutter#111] opened 2023-08-09 11:16 UTC
### MAX Plugin Version

2.6.0

### Flutter Version

3.10.6

### Device/Platform Info

Android 10

### Current Behavior

I'm using apploving with admob mediation. I'm using `com.google.ads.mediation:applovin:11.10.1.0` plugin for mediation.
However I need to call `setHasUserConsent`, `setIsAgeRestrictedUser` and `setDoNotSell`, so I'm using applovin max flutter plugin to do this before initializing `google_mobile_ads`.

I've got the following error on crashlytics:

```
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at com.applovin.applovin_max.AppLovinMAX.lambda$initialize$0(AppLovinMAX.java:14)
       at com.applovin.impl.sdk.o$2.run(:32)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7397)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

### Expected Behavior

No exception

### How to Reproduce

1. request user consent using `google_mobile_ads`
2. call `AppLovinMAX.setHasUserConsent(true);` or `AppLovinMAX.setHasUserConsent(false);`

here's a shortened version of code being executed:

```dart
Future<void> initAds() {
  final config = RequestConfiguration(testDeviceIds: testIds);
  MobileAds.instance.updateRequestConfiguration(config);
  
  // requestConsent function goes through google_mobile_ads ConsnetForm flow
  return requestConsent().then((value) async {
    AppLovinMAX.setHasUserConsent(true);
  }).catchError((err) {
    AppLovinMAX.setHasUserConsent(false);
  }).then((value) async {
    AppLovinMAX.setIsAgeRestrictedUser(false);
    AppLovinMAX.setDoNotSell(true);

    await MobileAds.instance.initialize().then((v) {
      if (kDebugMode) {
        v.adapterStatuses.forEach((adapter, status) {
          debugPrintSynchronously('$adapter: $status');
        });
      }
    });
    
  }).catchError((err) {
    debugPrint(err)
  });
}
```

**Comment by lesnitsky** [comment] 2023-08-14 11:18
As per [this section(https://developers.google.com/admob/android/mediation/applovin) on android integration, I need to call `setHasUserConsent` , `setIsAgeRestrictedUser`, `setDoNotSell` to comply with GDPR and CCPA.

**Comment by alhiwatan** [comment] 2023-08-15 11:02
You are right, but I'm talking about the Admob functions.  Our AppLovin plugins are designed to support various mediation networks, so publishers like you do not need to call the mediation networks' functions directly.  In other words, our AppLovin plugins work only with the AppLovin MAX.

**Comment by alhiwatan** [comment] 2023-08-18 06:10
Closed as not a bug.   I guess you called both `AppLovinMAX.initialize()` and `MobileAds.instance.initialize()`.   Since `AppLovinMAX.initialize()` will initialize all the plugins, `MobileAds` gets initialized twice.   This might be a reason, but not sure.  Anyway, this is out of our scope.

**Closed by alhiwatan** 2023-08-18 06:10 UTC
Labels: bug

**Comment by nikorehnback** [comment] 2024-01-09 04:36
Also seeing this crash with some users using `applovin_max: ^3.3.0`

Admob mediation is enabled per documentation and we call only `AppLovinMAX.initialize()`

@alhiwatan could you elaborate a bit why this is out of your scope?

**Comment by maitycyrus** [comment] 2024-02-28 09:37
Same here:

```
Dart SDK 3.2.5
Flutter SDK 3.16.8
applovin_max 3.7.0

```

```
Fatal Exception: java.lang.IllegalStateException
Reply already submitted
io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:435)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:272)
com.applovin.applovin_max.AppLovinMAX.lambda$initialize$0 (AppLovinMAX.java:341)
com.applovin.impl.sdk.n.a (SourceFile:1027)
android.os.Handler.handleCallback (Handler.java:883)

com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
```

**Comment by maitycyrus** [comment] 2024-02-28 09:59
@alhiwatan please reopen this issue as a bug. Otherwise we would need to create the same issue as a fresh but. Thanks!

**Comment by thomasmso** [comment] 2024-02-28 10:08
@nikorehnback - This plugin is meant to be used for integrations using MAX mediation. If you choose to use AdMob, their support team needs to support you on adding networks (not just AppLovin) correctly.

@maitycyrus - Are you using MAX mediation? Could you open a new issue if so? Your observation is intriguing and this crash might have a different cause than the original issue posted in the thread.

**Comment by maitycyrus** [comment] 2024-02-28 10:45
Thanks @thomasmso! I opened a new one [https://github.com/AppLovin/AppLovin-MAX-Flutter/issues/186](https://github.com/AppLovin/AppLovin-MAX-Flutter/issues/186)
