### ISSUE TITLE
com.applovin.adview.AppLovinFullscreenActivity.onDestroy

### ISSUE THREAD

**Issue by RaymondGsc** [AppLovin/AppLovin-MAX-Flutter#215] opened 2024-05-17 02:41 UTC
### MAX Plugin Version

3.9.2

### Flutter Version

3.19.6

### Device/Platform Info

Android

### Current Behavior

![image](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/8847253/ad1076af-76a0-4582-a3bc-7be2a5d47f65)

Same error as [this](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/372)  

### How to Reproduce

/

**Comment by centy** [comment] 2024-05-19 11:54
I have the same:
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:6148)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:6180)
  at android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:47)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:180)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:98)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2685)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:230)
  at android.os.Looper.loop (Looper.java:319)
  at android.app.ActivityThread.main (ActivityThread.java:8893)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:608)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.applovin.impl.sdk.k.a(com.applovin.impl.oj)' on a null object reference
  at com.applovin.adview.AppLovinFullscreenActivity.onDestroy (SourceFile:1)
  at android.app.Activity.performDestroy (Activity.java:9236)
  at android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1491)
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:6135)


Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.19045.4412], locale pl-PL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
[√] Android Studio (version 2023.3)
[√] IntelliJ IDEA Community Edition (version 2023.3)
[√] VS Code (version 1.89.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
![image](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/581714/4ee75225-70c2-4b0b-84ac-59f14feedc73)

**Comment by alhiwatan** [comment] 2024-05-23 10:10
@RaymondGsc, it seems that it is a duplicate of [this issue](https://github.com/AppLovin/AppLovin-MAX-React-Native/issues/340).  If you have this line that will automatically pull the latest SDK version, you need to remove it from your gradle file; otherwise, you will get the SDK version beyond what we are certified against your version of our Flutter module.

```
implementation 'com.applovin:applovin-sdk:+'
```

**Comment by centy** [comment] 2024-05-23 11:34
I do not have
`implementation 'com.applovin:applovin-sdk:+'`
I think it is different issue

**Comment by thomasmso** [comment] 2024-05-23 18:04
This actually has been fixed with our latest Android SDK v12.5.0: https://github.com/AppLovin/Android-SDK/releases/tag/release_12_5_0.

Our Flutter plugin 3.10.0 will automatically pull that SDK in: https://github.com/AppLovin/AppLovin-MAX-Flutter/releases/tag/release_3_10_0.

**Closed by thomasmso** 2024-05-23 18:04 UTC
Labels: bug
