### ISSUE TITLE
Request for AppLovin MAX Plugin

### ISSUE THREAD

**Issue by elkhalifte** [AppLovin/AppLovin-MAX-Flutter#2] opened 2021-10-18 13:14 UTC
many developpers are waiting for this plugin .

**Comment by MrDeeKey** [comment] 2021-11-22 20:35
Yeah! I hope so too!

**Comment by elkhalifte** [comment] 2021-11-22 20:57
@MrDeeKey  you can use my applovin max plugin https://github.com/elkhalifte/flutter_applovin_max , 
ihave forked it from https://github.com/ioridev/flutter_applovin_max and fixed issues.
you can add it like that 

```
flutter_applovin_max:
    git:
      url: https://github.com/elkhalifte/flutter_applovin_max.git
```

**Comment by thomasmso** [comment] 2021-11-22 21:00
Thanks @elkhalifte for the stopgap - we'll have a plugin out by EoY (it'll be my personal Christmas project ;)) and that will have built-in optimization for higher revenue impact. I'll leave issue re-open for now until then.

**Comment by HPN0412** [comment] 2021-11-25 10:21
@elkhalifte 

> @MrDeeKey you can use my applovin max plugin https://github.com/elkhalifte/flutter_applovin_max , ihave forked it from https://github.com/ioridev/flutter_applovin_max and fixed issues. you can add it like that
> 
> ```
> flutter_applovin_max:
>     git:
>       url: https://github.com/elkhalifte/flutter_applovin_max.git
> ```

Sorry @elkhalifte 
I'm try using this repository and my project occur this error

`D/AppLovinSdk(14869): [AppLovinSdk]
D/AppLovinSdk(14869): ========================================
D/AppLovinSdk(14869): =====AppLovin SDK=====
D/AppLovinSdk(14869): ===SDK Versions===
D/AppLovinSdk(14869): Version: 10.3.5
D/AppLovinSdk(14869): Plugin Version:
D/AppLovinSdk(14869): Ad Review Version:
D/AppLovinSdk(14869): ===Device Info===
D/AppLovinSdk(14869): OS: 10 (Q - API 29)
D/AppLovinSdk(14869): GAID: <Enable verbose logging to see the GAID to use for test devices - https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK>
D/AppLovinSdk(14869): Model: Android SDK built for x86
D/AppLovinSdk(14869): Locale: en_US
D/AppLovinSdk(14869): Emulator: true
D/AppLovinSdk(14869): WVVC: 373018518
D/AppLovinSdk(14869): Tablet: false
D/AppLovinSdk(14869): ===App Info===
D/AppLovinSdk(14869): Application ID: ...........................
D/AppLovinSdk(14869): Target SDK: 30
D/AppLovinSdk(14869): ExoPlayer Version: -1
D/AppLovinSdk(14869): ===SDK Settings===
D/AppLovinSdk(14869): SDK Key:
D/AppLovinSdk(14869): Mediation Provider: max
D/AppLovinSdk(14869): TG: 90
D/AppLovinSdk(14869): Test Mode On: true
D/AppLovinSdk(14869): Verbose Logging On: false
D/AppLovinSdk(14869): ===Privacy States===
D/AppLovinSdk(14869): Please review AppLovin MAX documentation to be compliant with regional privacy policies.
D/AppLovinSdk(14869):
D/AppLovinSdk(14869): Age Restricted User - No value set
D/AppLovinSdk(14869): Has User Consent - No value set
D/AppLovinSdk(14869): "Do Not Sell" - No value set
D/AppLovinSdk(14869): ========================================
D/AndroidRuntime(14869): Shutting down VM
E/AndroidRuntime(14869): FATAL EXCEPTION: main
E/AndroidRuntime(14869): Process: ...................................., PID: 14869
E/AndroidRuntime(14869): java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/AndroidRuntime(14869): 	at com.applovin.impl.mediation.e.a(Unknown Source:14)
E/AndroidRuntime(14869): 	at com.applovin.impl.mediation.MediationServiceImpl.collectSignal(Unknown Source:28)
E/AndroidRuntime(14869): 	at com.applovin.impl.mediation.b.b$2.run(Unknown Source:26)
E/AndroidRuntime(14869): 	at android.os.Handler.handleCallback(Handler.java:883)
`
Do you know about this issue?
Glad to have your help.

**Comment by elkhalifte** [comment] 2021-11-25 14:00
Hello @HPN0412 
can you show me how you are showing banner ads.

try something like this:
```
BannerMaxView(
                              (AppLovinAdListener? event) => print(event),
                              BannerAdSize.banner,
                              "unit ad here",
                              "unique key string")
```

**Comment by superkeka** [comment] 2021-11-25 14:29
> SDK Key:

It looks like the Applovin SDK key is empty

**Comment by elkhalifte** [comment] 2021-11-25 17:29
@superkeka you should initialize the plugin on app start.

**Comment by leon6003** [comment] 2022-01-05 09:40
Hi @elkhalifte ,

where do i put 

lutter_applovin_max:
    git:
      url: https://github.com/elkhalifte/flutter_applovin_max.git
      
and which issues are fixed ?

**Comment by johnmollaghan** [comment] 2022-01-25 22:37
Any update on this Applovin Fllutter Plugin?
Will it support bidding for Facebook Audience Network? Thanks

**Comment by johnmollaghan** [comment] 2022-01-26 08:50
Hi Thomas,

Which Unofficial plugin would you recommend?  Do you know if it would
support bidding for Facebook Audience Network?

Thanks

John

**Comment by thomasmso** [comment] 2022-01-26 08:55
There's one mentioned earlier in the thread - since we don't support it officially, I would not be able to comment further on it.

**Comment by johnmollaghan** [comment] 2022-01-26 08:59
Ok, I can try that.

**Comment by johnmollaghan** [comment] 2022-01-26 09:39
I am with Appodeal at the moment. I am not able to use Google Ads as my
account was terminated by Google. I have no idea why as I was not in
violation, just one of those things.

I was wondering would Applovin be a good alternative to Appodeal.

With Appodeal I am using Facebook Audience Network and also the ads that
Appodeal serve (these include Applovin but I don't need an account or an
app, I use the ads they get from Applovin I think)

If I went to Applovin Max and just used Applovin and Facebook (with
bidding), would that give me a high fill rate or would I need more networks?

I don't want to have to create apps across lots of networks as I have a lot
of apps.

Thanks

**Comment by thomasmso** [comment] 2022-01-26 09:43
Generally speaking the more the merrir, but it also depends on the geos your main users are in. A lot of networks we support are geo specific (e.g. Yandex for Russia). I'm not able to comment further on recommendations.

**Comment by Nikolaisd** [comment] 2022-01-26 09:55
Hi John. 
(I am not part of the Applovin team, but a user of their products).

 I would recommend reaching out to their customer support directly on their website regarding your questions, they reply promptly and even helped me set up my mediation and recommended ways of improving CPM and fill rates. 
I am very happy with my experience with Applovin. I switched from AdMob and was able to improve CPM and fill rates. I am running seven networks in my waterfall. 

Just waiting for the Flutter plugin so I can migrate all my users from Swift to a new Flutter version, as the non-official plugin does not implement best practices, and does not offer as much control.

**Comment by thomasmso** [comment] 2022-01-26 10:04
Hi @Nikolaisd - Appreciate all the positive feedback. Which customer support channel are you referring to? The Flutter plugin is on the back of my mind for a while now, but we're tied with higher-priority projects with all the publishers migrating over to our platform from MoPub.

**Comment by Nikolaisd** [comment] 2022-01-26 10:21
Great work deserves positive feedback. I was referring to support@applovin.com. 

When I first signed up for MAX one had to "request access", and I had a few skype meetings with a Mary K. regarding this, she later helped with the above mentioned. You also promptly helped when I had the issues with mute.caf and its static noise on iOS a few years ago. So all round great help.

I could imagine the MoPub migration being a lot of work.

**Comment by thomasmso** [comment] 2022-01-26 19:18
@Nikolaisd - Awesome, I'll forward it to my teammates who handle that alias, the `mute.caf` issue (I actually still recall it as well), and Mary K.

**Comment by thomasmso** [comment] 2022-01-26 19:19
@johnmollaghan - Reach out to me at thomas.so@applovin.com with your portfolio and I'll connect you with the right people.

**Comment by Nikolaisd** [comment] 2022-01-31 11:13
@thomasmso I am working on a fork of the above mentioned Flutter plugin, and adding more control to it. I had a quick question i was hoping you could help with. The iOS Max documentation states that impression level revenue is in USD
in the didPayRevenue callback, will it always be returned in USD?

**Comment by thomasmso** [comment] 2022-01-31 22:06
Correct, will always be USD

**Comment by ioridev** [comment] 2022-02-05 14:23
I can also transfer the repository.

**Comment by ioridev** [comment] 2022-02-05 14:30
@elkhalifte 
If you fix any of my unofficial plugins, send me a pull request and I'll update it. Thanks.

**Comment by ioridev** [comment] 2022-02-05 14:43
When the official plugin is released, I plan to discontinue my plugin. So you can transfer package ownership if you wish.

**Comment by w0ts0n** [comment] 2022-02-15 01:25
Just another +1 that I need this working for our app. Would prefer not to use 3rd party. Hopefully you can get to this soon.

**Comment by Vollinator** [comment] 2022-03-22 07:28
@thomasmso do you have any updates for us? I am really looking forward to the official SDK.

Thanks!

**Comment by thomasmso** [comment] 2022-03-22 07:36
Unfortunately not - we're still actively working on transitioning the thousands of publishers from MoPub over to MAX. After that migration ends we will pick this up.

**Comment by Vollinator** [comment] 2022-03-22 07:45
> Unfortunately not - we're still actively working on transitioning the thousands of publishers from MoPub over to MAX. After that migration ends we will pick this up.

Okay, thanks for your answer! 👍

**Comment by Vollinator** [comment] 2022-05-04 09:40
@thomasmso sorry for disturbing again. 
Is there any planned releasedate of the official SDK for Flutter? 

Thanks!

**Comment by thomasmso** [comment] 2022-05-04 09:53
Getting to it soon, now that the MoPub migration has settled. No hard ETA but likely this summer.

**Comment by Nikolaisd** [comment] 2022-05-04 09:58
I am also looking forward to the official Flutter SDK being released. 

@Vollinator 
But in the meantime the previously mentioned package by @ioridev does work. I am currently running it on a live production app with no issues. 

Unfortunately it is missing a few things such as revenue callback, setting GDPR flag, and running multiple different ad unit ids, but I manage for now.

**Comment by Vollinator** [comment] 2022-05-04 10:05
@Nikolaisd I have some problems with the package like performance, banner ads for ios, missing native ads and some more. In principle, it is a nice package, but unfortunately there are no more updates.

What is the advantage of running multiple different ad unit ids? Is it like multiple ids for banner ads?

**Comment by johnmollaghan** [comment] 2022-05-04 10:07
I am currently using the AppoDeal Flutter plugin.
It allows me to link to Facebook (Meta) and it uses AppLovin too.
Would Applovin Max be better from a revenue point of view?
Anyone else used both to be able to compare? Don't want to rewrite chunks
of the app only to discover no difference between them.

**Comment by davidgalarza** [comment] 2022-05-13 20:21
Any update?? We're really waiting for a long time for the oficial package.

**Comment by vishalknishad** [comment] 2022-05-19 16:04
Hey @thomasmso, Interested to know whether any work has started on this.

**Comment by thomasmso** [comment] 2022-05-21 01:12
@vishalknishad - Going to dig out some time this weekend and begin

**Comment by canewsin** [comment] 2022-06-05 15:39
@thomasmso Does Official plugin uses native Dart only Widgets API or Same as Platform Views with Webview as other ads plugins, Currently Flutter had become main stream and supports more platforms, but why all these plugins uses native views instead of Dart Widgets API.

**Comment by thomasmso** [comment] 2022-06-06 00:39
@canewsin - So far, it's programmatic only. Release after will take advantage of Platform Views or Widgets API - not sure on the tech requirements / preferences for which yet though, any insights would be appreciated

**Comment by laurentiu0** [comment] 2022-06-17 21:08
Is there an ETA for the launch? @thomasmso

**Comment by hkpatel201** [comment] 2022-06-18 07:52
Is there any update for the official plugin? As waiting for longtime 🙇

**Comment by leatdev** [comment] 2022-06-18 16:54
please when the official plugin will be out ? @thomasmso

**Comment by thomasmso** [comment] 2022-06-20 09:08
Have the initial version here: https://github.com/AppLovin/AppLovin-MAX-Flutter/pull/6

Will publish the flutter package shortly after

**Comment by thomasmso** [comment] 2022-06-20 09:32
To integrate mediated networks - you'll have to follow instructions here in the native projects ([Android docs](https://dash.applovin.com/documentation/mediation/android/mediation-adapters), [iOS docs](https://dash.applovin.com/documentation/mediation/ios/mediation-adapters)).

I've seen some other plugins automatically bundle these networks with it, which causes several issues:

1. Some networks have specific integration instructions (such as cleartext traffic), and
2. By bloating your app with networks that you don't use, your performance suffers as those SDKs may still take up device resources

**Comment by Vollinator** [comment] 2022-06-20 09:36
Thank you very much, I love it!
Could you give us please a quick introduction how to implement the library from this repo into the flutter application?

**Comment by thomasmso** [comment] 2022-06-21 06:17
Plugin is live! Let me know if there are any issues! Will add support for banner/MREC via Platform Views or Widgets APIs later.

pub.dev page: https://pub.dev/packages/applovin_max
docs: https://dash.applovin.com/documentation/mediation/flutter/getting-started/integration

**Comment by thomasmso** [comment] 2022-06-21 08:20
@medalawi - Thank you :) You should place the `AppLovinQualityServiceSetup-ios.rb` file in `my_flutter_project/ios/AppLovinQualityServiceSetup-ios.rb`. Note that it is only necessary if you want to enable Ad Review.

**Comment by johnmollaghan** [comment] 2022-06-21 09:41
It is fantastic that there is now an Applovin Max Flutter plugin. I am using AppoDeal at the moment but would like to try Applovin Max also to see which would best suit my apps.  Appodeal is fine but I am earning through their Applovin account, not my own.

I am hoping that you or others on this group could answer a few short questions please?

1) If I am just using Apploxin Max and Meta (Facebook), will I get a good fill rate?  With Appodeal I am mainly making money from BidMachine, Applovin and Meta, I want to make sure I am still getting good fill with Applovin Max?

2) Does Applovin Max have a market place to make sure all requests are filled?

3) Has anyone experience with both Appodeal and Applovin Max? The ads in Appodeal can be annoying, lots of game ads. Does Applovin Max have a better spread of ads outside of games?

**Comment by hkpatel201** [comment] 2022-06-21 13:10
**I am getting following issue when testing this plugin from pub.dev**

apps\applovin_test\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:19: error: cannot access MaxAdListener
      flutterEngine.getPlugins().add(new com.applovin.applovin_max.AppLovinMAX());
                                ^
  class file for com.applovin.mediation.MaxAdListener not found
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by thomasmso** [comment] 2022-06-22 02:04
@johnmollaghan - Depending on your app's audience / geo / etc, we will have different recommendations. You should at least include AdMob in there though. We're also in the process of adding support for BidMachine - you should subscribe to our native repos ([Android](https://github.com/AppLovin/AppLovin-MAX-SDK-Android), [iOS](https://github.com/AppLovin/AppLovin-MAX-SDK-iOS)) to stay current with latest adapters, the UI will be released soon. The composition of the types of ads really depend on the demand makeup and what the partners (including AL) deem highest ROI for the impression.

@laurentiu0 - I was not able to reproduce this, [as the value should be a int string already](https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/master/applovin_max/ios/Classes/AppLovinMAX.m#L615). Glad to hear you got it working on your end though.

@hkpatel201 - If you can reproduce that in our example app, could you send it over?

**Comment by Nikolaisd** [comment] 2022-06-22 11:29
@thomasmso 
Hi Thomas. Nice to have an official Flutter plugin, currently working on the integration and noticed that Data Passing is not currently present in the plugin. Will this be added in the near future? 

- Nikolai

**Comment by laurentiu0** [comment] 2022-06-22 12:40
I  noticed that when I use .isInitialized()  it sais that this method is not implemented. So,  this is not a valid option to check and I believe that this would be the only on.

**Comment by thomasmso** [comment] 2022-06-23 08:12
@Nikolaisd - We can add targeting API to the plugin, I likely won't have time to get to it until next week though.

@laurentiu0 - I have a fix here: https://github.com/AppLovin/AppLovin-MAX-Flutter/pull/9, feel free to check it out. I can push it sometime soon.

@johnmollaghan - `AppLovinSDK` has deployment target of iOS 10, so I'm not terribly sure on the issue as well without the project / reproducible case.

**Comment by johnmollaghan** [comment] 2022-06-23 12:53
OK, on Android I have deployed the plugin to a live app and it seems to be working well for Applovin Interstitials and banners.
However, I am also using META (I have included the dependancy in my build.gradle etc).
I added two new placements in META just for the applovin mediation (one for interstitial one for banner), so I can make sure there are requests and impressions coming from mediation.
The META interstitial placement is getting requests and serving impressions which is good. However, there are no ad requests or impressions for the META banners.
This is very strange, I would have expected lots of META banner requests and impressions.
Any ideas?

**Comment by thomasmso** [comment] 2022-06-23 17:03
You can check out the docs here: https://dash.applovin.com/documentation/mediation/flutter/testing-networks/mediation-debugger#sharing-the-mediation-debugger

**Comment by johnmollaghan** [comment] 2022-06-23 17:26
Excellent, thanks.

**Comment by johnmollaghan** [comment] 2022-06-23 17:29
Also, should I expect to see Mediation Reports under the Applovin Max part of the website?

If I pick Performance or any other report, I see this...
Unable to run the report
Unknown Error

I can see the Applovin earnings in the section above, but none of the Applovin Max reports work.

**Comment by thomasmso** [comment] 2022-06-23 18:23
For non-technical issues, can you email support@applovin.com?

**Comment by AsjadSiddiqui** [comment] 2022-07-08 19:21
@thomasmso When using the plugin, I found an issue on Android.
When I user Rewarded Ads, the Server Side Reward Callback is never called.

**Closed** 2023-05-06 17:25 UTC
