### ISSUE TITLE
Reward ad not showing

### ISSUE THREAD

**Issue by Fanom2813** [AppLovin/AppLovin-MAX-Flutter#98] opened 2023-06-30 22:56 UTC
### MAX Plugin Version

3.0.1

### Flutter Version

3.10.3

### Device/Platform Info

iOS X

### Current Behavior

I am mixing Reward, Interstitial, banner and MRECs ads in my app all are working only Reward ad not showing , the debug console shows `[AppLovinSdk] ERROR [MARewardedAd] Can not load another ad while the ad is showing` What could be the problem thanks 

### How to Reproduce

i am using the following code snippet to load the Reward ad 
 ```
AppLovinMAX.loadRewardedAd(rewardUnit);
  final isReady = await AppLovinMAX.isRewardedAdReady(rewardUnit);
  if (isReady == true) {
    AppLovinMAX.showRewardedAd(rewardUnit);
  }
```

**Comment by alhiwatan** [comment] 2023-07-10 12:08
Hello @Fanom2813,  the error is logged, as described in the message, when trying to load an ad before the current ad is hidden.   Can you load a new ad after closing the current ad or getting an event in `AppLovinMAX.addRewardedAdHiddenEventListener()`?   The same thing should happen with Interstitial ads.

**Comment by ycv005** [comment] 2023-07-31 16:32
Hello @thomasmso facing same issue. No real or test ads are visible. Tried with testing device & check the verbose and debugger as well.

**Comment by thomasmso** [comment] 2023-07-31 20:38
@ycv005 - Could you enable and send over our SDK's [verbose logs](https://dash.applovin.com/documentation/mediation/flutter/getting-started/advanced-settings#enable-verbose-logging) while in [test mode](https://dash.applovin.com/documentation/mediation/flutter/testing-networks/mediation-debugger#testing-with-test-ads)? That way we can diagnose the issue better.

**Comment by ycv005** [comment] 2023-08-02 07:32
Reward ads from my end is resolved.

**Comment by Fanom2813** [comment] 2023-08-02 07:35
how did you fixit ?

**Comment by ycv005** [comment] 2023-08-04 06:32
@Fanom2813 Follow this - https://github.com/AppLovin/AppLovin-MAX-Flutter/issues/40#issuecomment-1660901307

**Comment by ycv005** [comment] 2023-08-15 05:58
@thomasmso  For the Rewarded ads, unity ads are visible but incase of meta ads, in meta console, it says, format not supported.
![WhatsApp Image 2023-08-15 at 11 18 55](https://github.com/AppLovin/AppLovin-MAX-Flutter/assets/26734819/1a9b2ae0-59a9-4b87-bf36-0c92947a7546)

**Comment by thomasmso** [comment] 2023-08-15 06:33
Looks like you set up a format called "Rewarded Interstitial" in your Meta dashboard. However, you should be setting up a Rewarded Video or the like.

**Comment by ycv005** [comment] 2023-08-17 09:07
@thomasmso thanks

**Comment by ycv005** [comment] 2023-08-27 06:57
@thomasmso , I can only found Rewarded Interstitial not Rewarded Vide. Let me know what I am missing or what you/team have been trying successfully to show meta reward ads.

**Comment by ycv005** [comment] 2023-09-05 20:42
@thomasmso @alhiwatan Sometime Rewards Ads is finished but the events are not trigger so that I could reward user. By the way, this is very less like 5 out of 100. How to debug this ?

**Comment by ycv005** [comment] 2023-09-22 07:26
@thomasmso @alhiwatan , How to cover this issue ? The case are increasing, & lot of user are complaining about this. 
1 - Do, We as app owner, get rewarded when user internet is slow from ad network?
2 - Can we apply other checks, even the user internet is slow, like reward ads are closed after 10 sec (minimum) and we didn't get event from internet, then can we reward user ?

Kindly help here.

**Comment by thomasmso** [comment] 2023-09-22 07:42
@ycv005 - If you want to reward the user on every rewarded video watch, then can you just use the 

```
onAdHiddenCallback: (ad) {
        ⋮
    },
```

callback?

**Comment by ycv005** [comment] 2023-09-22 08:11
@thomasmso But if someone open the reward ads and sudden close it, then ? 
In what case does this onAdHiddenCallback event will be trigger? 
I have check package code, didn't find the documentation.

If you please provide helpful documentation like when when this onAdHiddenCallback event will be trigger, it will be really really helpful.

**Comment by ycv005** [comment] 2023-09-22 09:13
@thomasmso  @alhiwatan 
By the way, I always had a call on onAdHiddenCallback, still missing events.
here are my code.

```
void _createAppLovinRewardAd(BuildContext context) {
    var rewardedAdRetryAttempt = 0;
    String rewardedAdUnitId =
        context.read<SystemConfigCubit>().applovinRewardedAdId();
    AppLovinMAX.setRewardedAdListener(
      RewardedAdListener(
          onAdLoadedCallback: (ad) {
            emit(RewardedAdLoaded());
            rewardedAdRetryAttempt = 0;
            firebaseService.logEventWithDefaults(
              name: describeEnum(CustomFirebaseEvent.ad_imp_reward),
              parameters: {
                describeEnum(CustomFirebaseDimension.adType): "RewardedAd",
                describeEnum(CustomFirebaseDimension.adNetwork): ad.networkName
              },
            );
          },
          onAdLoadFailedCallback: (adUnitId, error) {
            rewardedAdRetryAttempt = rewardedAdRetryAttempt + 1;

            emit(RewardedAdFailure());
            int retryDelay = pow(2, min(6, rewardedAdRetryAttempt)).toInt();

            Future.delayed(Duration(milliseconds: retryDelay * 1000), () {
              AppLovinMAX.loadRewardedAd(rewardedAdUnitId);
            });
          },
          onAdDisplayedCallback: (ad) {},
          onAdDisplayFailedCallback: (ad, error) {
            Future.delayed(const Duration(seconds: 2), () {
              AppLovinMAX.loadRewardedAd(rewardedAdUnitId);
            });
          },
          onAdClickedCallback: (ad) {},
          onAdHiddenCallback: (ad) {
            if (state is RewardedAdFullWatched) {
              emit(RewardAdInformUser());
            }
            Future.delayed(const Duration(seconds: 1), () {
              AppLovinMAX.loadRewardedAd(rewardedAdUnitId);
            });
          },
          onAdReceivedRewardCallback: (ad, reward) {
            _rewardUserAfterAdWatch(context);
            Future.delayed(const Duration(seconds: 1), () {
              AppLovinMAX.loadRewardedAd(rewardedAdUnitId);
            });
          }),
    );
    Future.delayed(const Duration(seconds: 1), () {
      AppLovinMAX.loadRewardedAd(rewardedAdUnitId);
    });
  }
```
and here is other function

```
  void _rewardUserAfterAdWatch(BuildContext context) {
    //ad rewards here
    //once user sees ad then add coins to user wallet
    String userId = context.read<UserDetailsCubit>().userId();
    int currentRewardCoins = context.read<SystemConfigCubit>().getRewardCoin();

    context.read<UpdateScoreAndCoinsCubit>().updateCoins(
          userId
        );
    emit(RewardedAdFullWatched());
  }
```
and here is code, when showAd is called

```
String rewardedAdUnitId =
              context.read<SystemConfigCubit>().applovinRewardedAdId();
          bool isReady =
              (await AppLovinMAX.isRewardedAdReady(rewardedAdUnitId))!;
          if (isReady) {
            AppLovinMAX.showRewardedAd(rewardedAdUnitId,
                placement: placementArea);
          } else {
            AppLovinMAX.loadRewardedAd(rewardedAdUnitId);
          }
```

**Comment by alhiwatan** [comment] 2023-12-11 07:32
Closing since the issue is not a bug.    

@ycv005, if you still have an issue with `onAdReceivedRewardCallback`, could you open a new issue with it ?

**Closed by alhiwatan** 2023-12-11 07:32 UTC
Labels: bug
